---
title: "Twitter study"
author: "me"
date: "February 28, 2017"
output: html_document
---

```{r setup, include=FALSE}
require(twitteR)
setup_twitter_oauth("vRb1BPv0mp85t5uk99MD5GdvY","vbEKOCu58TnGx3EKTmGyAV9zZ08nRYUCDvTrDfcw7dTR7Snf8k")
```

```{r}
searchTwitter("Berkeley",
              geocode='37.8719,-122.2585,1mi', 
              until="2017-02-28",
              since = "2017-02-26")
```

```{r}
data = read.delim(file = "C://Users/Erik Cheng/stat198/ICWSM2013_Paper_187_Data/all_streaming_api.txt", sep = "\n", header = FALSE, colClasses = c("character"))
```
  
  
```{r}
testing = function(k){
  out = (tryCatch(
    {
     showStatus(data[k,1]) 
    },
    error = function(cond){
      message(paste("bleh"), as.character(k))
      
    }
    
    )
  )
  return(out)
} 
testTweets = sapply(c(1:10), testing) 
getHandle = function(tweet){ #takes in tweet object and returns its handle
  return (tweet$screenName)
}
getTime = function(tweet) {
  return (tweet$created)
}
testHandles = sapply(testTweets, getHandle)
```

```{r}
timelines = sapply(testHandles,userTimeline, n = 3200)
```

```{r}
fullTweets = sapply(c(1:1000), testing)
```

```{r}
tweetTimes = sapply(fullTweets, getTime)
```

```{r}
nulls = (lapply(fullTweets,is.null))

```

